### ISSUE TITLE
[FEATURE] Post summer photometry to Fritz

### ISSUE THREAD

**Issue by robertdstein** [winter-telescope/mirar#221]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I take good data but it doesn't miraculously appear in Fritz.

**Describe the solution you'd like**
It to appear in Fritz. We have the relevant pieces already.

**Describe alternatives you've considered**
Not doing that. Slow but doable.

**Comment by robertdstein** [comment]
Possible with merging of #416

**Comment by saarahha** [comment]
duplicate
