### ISSUE TITLE
[FEATURE] Tests for SEDmv2

### ISSUE THREAD

**Issue by robertdstein** [winter-telescope/mirar#422]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when we change things, and are not sure how it impacts SEDmv2

**Describe the solution you'd like**
Add a test, end to end, for both a stellar image and a transient image.

**Comment by saarahha** [comment]
I will make a PR with the transient test now - @broulston, let me know if you can develop the stellar pipeline test. I tried to do it myself but got errors from the `image_photometry` block.
