### ISSUE TITLE
[FEATURE] Deprecate combine in Swarp

### ISSUE THREAD

**Issue by robertdstein** [winter-telescope/mirar#450]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I read the swarp processor, which is full of warnings that `combine` should always be true since it makes no difference.

**Describe the solution you'd like**
I want to deprecate combine as an argument (have it always be True). It seems like that unexpectedly makes a difference to the end data though.

**Comment by virajkaram** [comment]
We need combine=True for specific use-cases. Right now, we need it only for image subtraction, which is consistent with the imsub test failing for #449 . 
The warning in swarp has been updated accordingly and processors using combine=True catch the warnings and supress it. Closing.
