### ISSUE TITLE
[FEATURE] No way to load MEF images

### ISSUE THREAD

**Issue by virajkaram** [winter-telescope/mirar#468]
There is no way currently to load in a MEF file or the header of an MEF frame. This is required if we want to export info from a MEF primary header to a database table, as we want to do for the exposures table.

**Describe the solution you'd like**
1. New processor.
2. Nothing, trust users and deduplication in the database exporters to ensure that a single entry is made for every MEF.

**Comment by robertdstein** [comment]
This is a duplicate of #458 ?

**Comment by virajkaram** [comment]
Not really. MEFParser should pass on the split single extension data, while here we need the MEF image header itself.

**Comment by virajkaram** [comment]
Closed with #475
