### ISSUE TITLE
[BUG] WINTER photometric calibration is not reproducible

### ISSUE THREAD

**Issue by robertdstein** [winter-telescope/mirar#501]
**Describe the bug**
Repeating photometric calibration on a prototype test pipeline passes exactly sometimes, and on other occasions fails. The zeropoints are not always reproducible even on the same machine!

**Comment by robertdstein** [comment]
This may be related to a seemingly random ordering that can occur in the pipeline. Maybe we should be sorting images at each step? We should for sure be sorting pre-stacking.

**Comment by robertdstein** [comment]
Does not seem to have reoccurred. Will close, but reopen if needed.

**Comment by robertdstein** [comment]
Seems to be happening again

**Comment by robertdstein** [comment]
Hopefully fixed by #542

**Comment by virajkaram** [comment]
This was related to the non-deterministic order with which Scamp ran. In the current version, the results are exactly reproducible on the same device. There are slight differences (at ~1 % level) between my computer and github-CI, even with the same versions of the softwares on both devices that I haven't been able to track down. 
These differences are within the tolerance levels we set for zeropoints, but we can track them down sometime later if we want to.

**Comment by robertdstein** [comment]
Suggestion: print the CI values once, and then fix the tests to the Github CI values rather than your laptop. It'll give us more wriggle-room on tolerance.

**Comment by robertdstein** [comment]
Anyway, this issue of internal non-reproducibility seems to indeed have been fixed by #542
