### ISSUE TITLE
[BUG]WINTER pipeline stacking exposures of different durations

### ISSUE THREAD

**Issue by virajkaram** [winter-telescope/mirar#512]
**Describe the bug**
Some stacks from 20230713 have an effective exposure time of 190 sec., which does not make sense. Upon investigating, it seems like the pipeline stacked together 5 exposures of 30 sec. and 4 exposures of 10 sec. 

**To Reproduce**
Check e.g., /data/loki/data/winter/20230713/raw_unpacked/WINTERcamera_20230714-042207-530_mef_5_0_1.fits 

**Expected behaviour**
It stacks only the exposures with the same exptime by default.

**Comment by robertdstein** [comment]
We just need need to put "EXPTIME" in the Image Batcher I think: https://github.com/winter-telescope/mirar/blob/e9473928cdd58fec25e4d6c7155477d5d8b8064b/mirar/pipelines/winter/blocks.py#L334

**Comment by virajkaram** [comment]
Oh i thought it was doing that already but clearly was mistaken. that should solve it i also think.

**Comment by robertdstein** [comment]
I had also assumed this was there, and was also mistaken.
