### ISSUE TITLE
[BUG] ImageAperturePhotometry temp directory doesn't play nice with multiple cores

### ISSUE THREAD

**Issue by broulston** [winter-telescope/mirar#548]
**Describe the bug**
In `mirar.processors.photometry.aperture_photometry.ImageAperturePhotometry`  at the end of `_apply_to_images` the temporary folder is deleted. If running on multiple cores, this causes all images in the folder to be deleted, causing `FileNotFound` errors, and will fail the majority of the images in that processor.

**Comment by virajkaram** [comment]
We need to change this to only delete the temporary files and not the directory. 
Looks like `CandidateAperturePhotometry`, `ImagePSFPhotometry` and `CandidatePSFPhotometry` are the only other processors where this is happening so the same fix should be applied there.
