### ISSUE TITLE
[BUG] Incostistent TARGET_KEY usage in winter

### ISSUE THREAD

**Issue by virajkaram** [winter-telescope/mirar#551]
**Describe the bug**
I don't understand what TARGET_KEY is supposed to be. It is set to the `OBSTYPE` [here](https://github.com/winter-telescope/mirar/blob/a72830f9a54c8d2acb63733bf2fa9d690ae3b2f3/mirar/pipelines/winter/load_winter_image.py#L71), but seems to be used as a proxy for the name of the observed target in blocks.py (e.g. [here](https://github.com/winter-telescope/mirar/blob/a72830f9a54c8d2acb63733bf2fa9d690ae3b2f3/mirar/pipelines/winter/blocks.py#L201)).  
If it is the latter, we should rename it to `TARGET_KEY="TARGNAME"` (which I think is the official FITS keyword as it is present in the raw images that come off the mountain) and get rid of `TARGET_KEY="TARGET"`

**Comment by robertdstein** [comment]
We should stick to the fits definition. We have a separate obsclass key for science/dark/focus.
