### ISSUE TITLE
[BUG] Deterministic WINTER stackid from raw images

### ISSUE THREAD

**Issue by virajkaram** [winter-telescope/mirar#601]
**Describe the bug**
Determine winter stackid from raw images, to make it very deterministic, by adding a CustomImageBatchModifier processor.

**Comment by robertdstein** [comment]
Maybe we should just replace `CustomImageBatchModifier` with `CustomImageBatchModifier`, and have the functions do the for-loop over images? I can't see a downside to that, honestly.
