### ISSUE TITLE
[FEATURE] Carefully decide what images get used for WINTER flats

### ISSUE THREAD

**Issue by virajkaram** [winter-telescope/mirar#619]
**Is your feature request related to a problem? Please describe.**
WINTER flat-fielding happens with images that don't necessarily have a large numbers of counts. Looks like the dark counts vary on a level of few hundreds. If the sky counts in the flats are ~2000, this means that our winter frames would never be calibrated better than 10% (min. uncertainty is 0.1 mag, before including any other effects). This is very suboptimal. 

**Describe the solution you'd like**
We should set a threshold on the median number of counts in an image that should be used for flat-fielding, to improve the quality of reductions. This would probably translate to only using frames taken earlier during the evening. On an astro-note, we should probably be taking twilight flats.

**Comment by robertdstein** [comment]
I think this has been somewhat superseded by dome flats. See #835 instead.
