### ISSUE TITLE
[FEATURE] run source photometry on many sources without image subtraction

### ISSUE THREAD

**Issue by saarahhall** [winter-telescope/mirar#642]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I want to perform PSF photometry on all of the sources in my image, but the `SourceBatch`/`SourcePSFPhotometry` infrastructure requires that I run ZOGY first. It seems that the only way to generate a source table with several sources in it is to use `source_detector.py` which runs on a ZOGY difference image.

**Describe the solution you'd like**
I would like to have a class or function that will turn all the sources in a sextractor table into a candidate table, which I can then hand to the `Source{PSF/Aperture}Photometry` processors.

**Describe alternatives you've considered**
I've also considered shifting gears and setting up image subtraction first, to abide by the commonly expected workflow.

**Additional context**
I know that @robertdstein is restructuring sources in an upcoming PR, but the priority there is for single sources (to get pushed to Fritz) rather than a list of sources. I mentioned the ZOGY prereq before in the context of `source_exporter.py,` so it's possible your current work will accidentally fix this as well.

**Comment by robertdstein** [comment]
I think this is a great idea. A `SextractorSourceDetector`. We should discuss at the call.
