### ISSUE TITLE
[FEATURE] use Sextractor+PSFex to calculate PSF magnitudes

### ISSUE THREAD

**Issue by saarahhall** [winter-telescope/mirar#663]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when we see mysterious results when running `PSFPhotometry` on SEDMv2 data that hasn't undergone image subtraction (for example, the funky variable light curves we saw in one of @broulston 's stellar sources). The current `PSFPhotometry` processor assumes that the cutout in question has one source in it and no contamination, thus returning wonky results for dim sources with bright sources nearby. This can be seen in the plot below. 
![image](https://github.com/winter-telescope/mirar/assets/66533667/7264f470-3b9b-49cf-8258-84b92620c48a) (This plot was enabled by the incoming `SextractorSourceDetector` processor that would address #642)

**Describe the solution you'd like**
I'd like to add an option to run `Sextractor` with the `-PSF_NAME` argument (handing in a PSFex model) to enable `MAG_PSF` and `MAGERR_PSF` calculations.

**Describe alternatives you've considered**
I have also considered just reducing the cutout size within the `PSFPhotometry` processor.

**Comment by virajkaram** [comment]
I think Sextractor with PSF is a very useful addition.
The PSFEx processor stores the psf model name in the image header - https://github.com/winter-telescope/mirar/blob/9ca72c0266013c4050888892c006e07f22ec8577/mirar/processors/astromatic/psfex/psfex.py#L107, so I think you can just use that header key in Sextractor?
