### ISSUE TITLE
[BUG] CI intermittently running out of space?

### ISSUE THREAD

**Issue by virajkaram** [winter-telescope/mirar#689]
**Describe the bug**
```OSError: Not enough space on disk: requested 33554432, available 0. Not enough space on disk: requested 33554432, available 0. Not enough free space to write 33554432 bytes``` for https://github.com/winter-telescope/mirar/actions/runs/6328455167/job/17186661169?pr=688

**Comment by robertdstein** [comment]
Proposed solution: each test cleans up/deletes itself after running.
