### ISSUE TITLE
[BUG] Astrometry.net libgsl conda install issue

### ISSUE THREAD

**Issue by virajkaram** [winter-telescope/mirar#776]
**Describe the bug**
If we create a new conda environment and install astrometry-net using conda, it fails with error `libgsl.so.25 not found`. 
Seems like the latest versions of anaconda ship `libgsl.so.27`, which causes the issue. A solution is to downgrade the version of gsl, see here https://github.com/ParBLiSS/FastANI/issues/96.

Need to investigate a bit more.

**Comment by robertdstein** [comment]
Our CI installs gsl with conda:

https://github.com/winter-telescope/mirar/blob/f2f0df2309474324df403a9a69a3fc1bb21b0151/.github/workflows/continuous_integration.yml#L56

I think this should solve it? but may be worth updating docs
