### ISSUE TITLE
[FEATURE] Catch masquerading darks

### ISSUE THREAD

**Issue by robertdstein** [winter-telescope/mirar#878]
**Is your feature request related to a problem? Please describe.**
Images from WINTER are taken with the mirror cover closed.

We should:

- Get mirror cover status into the header, and filter out science images that have this marked closed (cc @nlourie for WSP end)
- Check each image, and revisit the dark oversubtraction error threshold

**Comment by virajkaram** [comment]
Would also be good to have the dark oversubtraction check in WSP @nlourie .

**Comment by robertdstein** [comment]
any non-dark image needs MIRCOVER=open, any other state (e.g opening) will be marked as bad image to be thrown away
